### ISSUE TITLE
ERROR WHILE RUN

### ISSUE THREAD

**Issue by sitxxar** [Punten10/SuperMeow-BOT#1]
![image](https://github.com/Punten10/SuperMeow-BOT/assets/37711440/315985b3-fee3-4ff4-be6f-215bd6b57561)

**Comment by Punten10** [comment]
u can try delete sessions.json

**Comment by sitxxar** [comment]
Thx, solved

Pada Jum, 14 Jun 2024 12.32 AM, Punten10 ***@***.***> menulis:
